### ISSUE TITLE
[list] todo list [20201210] 

### ISSUE THREAD

**Issue by Alice52** [Alice52/Alice52#14]
## from last list

- [x] 1.整理一下 spring boot 的异常机制 sample
- [x] 2.结束 ec-project 的基础篇

## issue list

-  [ ] 1.[完成 es 数据同步](https://github.com/Alice52/project/issues/96)

## deadline

- `20201220`

**Comment by Alice52** [comment]
> 1.整理一下 spring boot 的异常机制 sample

- [global-exception handler](https://www.cnblogs.com/jurendage/p/11255197.html)

**Comment by Alice52** [comment]
- [ ] 1.common-api
- [ ] 2.basic ec
- [ ] 3. es data sync
- [ ] 4.洗鞋
- [ ] 5.卫生

**Comment by Alice52** [comment]
~~3. es data sync~~
