### ISSUE TITLE
[list] todo list [20201012]

### ISSUE THREAD

**Issue by Alice52** [Alice52/Alice52#2]
- [x] easy doc
    - https://easydoc.xyz/

- [x] 101.132.45.28 server data migration

    - [x] dev-kibana: this server will occupy large memory, so will run it in other server later
    - [x] dev-nacos-standalone: this server will occupy large memory, so will run it in other server later
    - [x] dev-mysql: need migration data
    - [x] dev-redis-standalone
    - [x] dev-redis-cluster
    - [x] dev-rmqnamesrv
    - [x] dev-rmqbroker
    - [x] dev-rmqconsole
    - [x] dev-tutorial-encrypt

- [x] purcharse server in tx

   - xt:
   - ali: others server just run specified service, such as nacos and mq

- [ ] ~~run ec-project in server~~

   - limit nacos start-up OPT[memory], it will lead to server crash for less memory
   - limit gateway memory due to it just gateway and start-up on netty

- [x] run instance of elastic-serach and kabana
   - then consider to run instance of log-stash
   - cluster env build
