### ISSUE TITLE
[list] todo list [20210621]

### ISSUE THREAD

**Issue by Alice52** [Alice52/Alice52#31]
## 1.设计模式

- move to labal design

## 4.MySQL

1. 优化
2. 分库分表
3. 多数据源

## 6.Redis

~~1. 使用~~
~~2. 协议~~
~~3. 数据一致性: MySQL & Redis`[CAP]`~~
~~4. Hash 一致性算法~~

## 7.微服务

- move to java-ocean

## 9.Java - 并发 & 线程池
1. AQS
2. ThreadLocal
3. [SPI:JDK/Dubbo/Spring](https://mp.weixin.qq.com/s?__biz=MzUxOTAxODc2Mg==&mid=2247490338&idx=1&sn=e653a4bc5f78b9fcc99b0188cec4d46c)

## 10. 设计题

- move to system labal

## 11. Common

- [ ] 1. DDD
- [ ] 2. Reactor
- [x] 3. HTTP 的连接
- [x] 4. HTTP1.0和HTTP1.1和HTTP2.0的区别
- [x] 5. 接口幂等问题
- [x] 6. 分布是唯一Id生成

## 12.Java-Common

- [ ] 1. inner class --> lambda --> stream --> functional
- [ ] 2. generic --> reflect --> interface --> enum --> exception
- [ ] 3. collection --> map
- [ ] 4. io
- [ ] 5. static --> classLoader --> jvm --> agent
- [ ] 6. thread --> juc
- [ ] 7. optional & DateTime
- [ ] 8. annotation --> proxy --> strategy mode
- [ ] 9. test --> jmeter --> jhm

## 13.RPC

~~1. gRPC~~
~~2. Dubbo~~
~~3. 设计一个 RPC 框架要考虑的因素~~

## 14.Others

~~1. 扫码之后发生了什么?~~
~~2. URL 输入发生了什么?~~
1. move to java-ocean

## 15.Algorithms

- [x] 1. 排序算法
- [x] 2. 红黑树
- [x] 3. b/b+树
- [x] 4. redis - LRU/LFU
- [x] 5. 分布式ID方案 - 雪花算法
- [x] 6. 常见的算法题(剑指offer)

## 16.开放性问题

~~1. 自我介绍 + 项目介绍~~
~~2. 项目中遇到什么问题难点 +  怎么解决~~
~~3. 你有什么职业规划~~
~~4. 有什么优势 + 为什么~~
~~5. 有什么印象深刻的经历~~

**Comment by Alice52** [comment]
## DDD

1. [供应链实现](https://mp.weixin.qq.com/s/oEotZ9Sueus-LGZWPoy_RQ)

**Comment by Alice52** [comment]
## legacy issue

- [ ] 1. 百度 Uid 的原理
