### ISSUE TITLE
[blog] 2021-07

### ISSUE THREAD

**Issue by Alice52** [Alice52/Alice52#38]
## subject

1. Bean
2. http

## blogs

- [ ] 1. [spring-bean](https://mp.weixin.qq.com/s/Nr0Ds-_OSr9lKZfHJalVBA)
- [ ] 2. [tcp](https://mp.weixin.qq.com/s/-t6fS_Hif9jDPsuMlWWeyQ)
- [ ] 3. [redis-qiuck](https://mp.weixin.qq.com/s/tV4kmJcnqAoE0Victuu6mg)
- [ ] 4. [spring-bean](https://mp.weixin.qq.com/s/Rl5x9lGVQr3NQKTJ9ARotw)
- [ ] 5. [redis-struct](https://mp.weixin.qq.com/s/HQA8Tcg4a1oElvUBSNlN_A)
- [ ] 6. [synchronize](https://mp.weixin.qq.com/s/eJLvyoIvHKZ15i8aTZoOBQ0)
- [ ] 7. [dns](https://mp.weixin.qq.com/s/eaD1Hedtl_3atbLsbanTqw)
- [ ] 8. [redis-quick](https://mp.weixin.qq.com/s/wf08G3PHpfbJKiU7ZVO9Lw)
- [x] 9. [贪心算法](https://mp.weixin.qq.com/s/yDVQ_18kQoB-Z-yluklwuw)
- [ ] 10. [redis-useage](https://mp.weixin.qq.com/s/0c84osfx1DzzGV3mVsU7xQ)
- [ ] 11. [cas](https://mp.weixin.qq.com/s/pgujTsi3NI94PtHXn9eQDg)
- [ ] 12. [order by](https://mp.weixin.qq.com/s/h9jWeoyiBGnQLvDrtXqVWw)
- [ ] 13. [分库分表](https://mp.weixin.qq.com/s/F7MwdaJKZMocHIcDIJl-aA)
- [ ] 14. [mysql-AI](https://mp.weixin.qq.com/s/Rw4IwpgtbQt4erGnt5Omcg)
- [ ] 15. [mysql](https://mp.weixin.qq.com/s/1PcaYPKAshFz6D93BsCaDA) : 考虑如何避免回表的问题
- [ ] 16. [分布式设计](https://mp.weixin.qq.com/s/n2PwDggzxTCOiuV2-w3hRA)
- [ ] 17. [mysql-bug](https://mp.weixin.qq.com/s/MpKhOI7ukGiEVLq16tyjug)
- [ ] 18. [nginx](https://mp.weixin.qq.com/s/SG5em-Za-KDnhNT4ZJRBkg)
- [x] 19. [thread talk](https://mp.weixin.qq.com/s/y4Y6Ghzm-ECtg0LeDdCZHQ)
- [ ] 20. [二维码](https://mp.weixin.qq.com/s/UdTJmmvXy-dSMtGPUEnFSg)
- [ ] 21. [inno-db](https://mp.weixin.qq.com/s/CkZMYAzXyyWk1LA--nAzTg)
- [ ] 22. [gateway](https://mp.weixin.qq.com/s/aSCwsq6hFhpwANtmH0KVeA)
- [ ] 23. [order by](https://mp.weixin.qq.com/s/lEtvcRwPAj5mieJcfnaFSQ)
- [ ] 24. [bean](https://mp.weixin.qq.com/s/HC07P7RQbH-CzS5nCRaonw)
- [ ] 25. [grpc](https://mp.weixin.qq.com/s/CIOwLqa3SlORz0WAucg3Xg)
- [ ] 26. [cache system](https://mp.weixin.qq.com/s/NcHuIJkMnkYFcIY3u729gQ)
- [ ] 27. [spi](https://mp.weixin.qq.com/s/0sFQ88Qiop-ElizcxA9huA)
- [ ] 29. [design pattern](https://mp.weixin.qq.com/s/z0qLwzcGzQDiLIKJa3eDfQ)
- [x] 30. [design pattern](https://mp.weixin.qq.com/s/MP3uq4gGxMlec_drA_7GJQ)
- [ ] 31. [分布式事务](https://mp.weixin.qq.com/s/_zhntxv07GEz9ktAKuj70Q)
- [ ] 32. [design pattern](https://mp.weixin.qq.com/s/JC0VMp7l8XQTwKdS7xRIHA)
- [ ] 33. [spi](https://mp.weixin.qq.com/s/EHxnzjANziuxq86XOQCElQ)
- [ ] 34. [分布式事务](https://mp.weixin.qq.com/s/q3MsMDtqrUGDfnggAF8-RQ)
- [ ] 35. [redis 缓存一致性](https://mp.weixin.qq.com/s/_XiStcc1e13RrY-WNTrgHg)
- [ ] 36. [mybais](https://mp.weixin.qq.com/s/V--uVjMTf0dk-MPcQUidRw)
 

## dimension

1. xx

## conclusion

1. xx
2. xx

## task

- [ ] 1.xx

## question

- [ ] 1.xx
