### ISSUE TITLE
[blog] 2021-07-14

### ISSUE THREAD

**Issue by Alice52** [Alice52/Alice52#39]
## outline

1. `blog`

## tasks

- [x] ~~1.[算法心得](https://mp.weixin.qq.com/s/pBX7HB9bG9A2Cii3JYVM_g)~~
- [x] 2.[order by详解](https://mp.weixin.qq.com/s/h9jWeoyiBGnQLvDrtXqVWw)
- [x] ~~3.[组合对象](https://mp.weixin.qq.com/s/qkmfvOv9ZeT6EI5HFrNrBQ)~~: 不知道在说什么
- [x] 4.[正排倒排](https://mp.weixin.qq.com/s/lEtvcRwPAj5mieJcfnaFSQ)
- [x] 5.[ThreadLocalRandom](https://mp.weixin.qq.com/s/5LnjSv4wb8B0xbRUqvkkng)
- [x] 6.[单点登录](https://mp.weixin.qq.com/s/m_PpC2QSpJvb_7uH0xM3mw)
- [x] 7.[interface](https://mp.weixin.qq.com/s/o_rYSX0zoKmHgfoIs6zqxg)
- [x] 8.[list deduplicate](https://mp.weixin.qq.com/s/EjaAO6bDq1wLWH2w4GZo8w)
- [ ] 9.[cros](https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzI0MTUwOTgyOQ==&action=getalbum&album_id=1907899736917884936)
- [x] 10.[localtime](https://mp.weixin.qq.com/s/RBvJ91J_wiXNdJG8MeW00A)
- [x] 11.[重复支付](https://mp.weixin.qq.com/s/RvAmMGWmtIkLLhkSITjN6g)
- [ ] 12.[分布式锁](https://mp.weixin.qq.com/s/imM3_MIp6CS_8DVL8bGr_Q)
- [x] 13.[反斜杠 \\](https://mp.weixin.qq.com/s/MpKhOI7ukGiEVLq16tyjug)
- [x] 14.[java-lock](https://mp.weixin.qq.com/s/HVHrCDFWXIp9r3uvXBHN8w)
- [x] 15.[线程池](https://mp.weixin.qq.com/s/VQPXrPcFxnaKJ4geP-mRww)

--- 

## conclusion

1. lock.lock() 一定要写在 try 外面, lock.unlock() 写在 finally 里
2. Service 层是否需要接口
    - AFAI, 需要使用接口, 调用接口 + 多实现`[强制规范]` + spring aop[cglib]
3. 线程池: 先放入 queue 而不是创建线程的原因是资源消耗, 有可能是激增的流量啦[不会持久]
4. 重复支付: `支付中的状态 + 各种幂等考虑 + 支付回调的异常主动查询支付结果`
