### ISSUE TITLE
[list] todo list [20201110]

### ISSUE THREAD

**Issue by Alice52** [Alice52/Alice52#8]
## issue list

- [x] ~~1.整理一下 spring boot 的异常机制 sample~~
- [x] ~~2.结束 ec-project 的基础篇~~
- [x] 3.build and deploy by travis and docker
- [x] 4.[es data sync](https://github.com/Alice52/project/issues/96)
- [x] 5.migration `travis-ci` to `github action`
- [x] 6.install ubunu in pc

## deadline

`20201128`

**Comment by Alice52** [comment]
> 5.migration travis-ci to github action

- [offical-docs](https://github.com/marketplace/actions/build-and-push-docker-images#usage)
- [reference](https://www.jianshu.com/p/0a0517291689)

**Comment by Alice52** [comment]
> 1.整理一下 spring boot 的异常机制 sample

- [global-exception handler](https://www.cnblogs.com/jurendage/p/11255197.html)

**Comment by Alice52** [comment]
> deadline

`20201128` + `7`
